export const team = [
  {
    img: "/assets/equipo/Bernal.jpg",
    name: "Nicolás Bernal Benítez",
    role: "Nico",
    carrera: "Ingeniería Cibernética",
    frase:"Memento Mori",
    experiencia:"Excelente",
  },
  {
    img: "/assets/equipo/Arredondo.png",
    name: "Michelle Arredondo",
    role: "Mich",
    carrera: "Diseño Gráfico y Digital",
    frase:"La vida es una",
    experiencia:"Mucho apoyo de todos",
  },
  {
    img: "/assets/equipo/Avila.jpg",
    name: "Brenda Ávila Jiménez",
    role: "Bren",
    carrera: "Diseño Gráfico y Digital",
    frase:"No sueñes tu vida, vive tu sueño ",
    experiencia:"Es muy tranquilo y el trabajo que hacemos es imprescindible para tener los resultados que generamos ",
  },
  {
    img: "/assets/equipo/Piña.png",
    name: "Rafael Piña",
    role: "Rafa",
    carrera: "Diseño Gráfico y Digital",
    frase:"Me encata todo",
    experiencia:"Me facino, trabaej mucho",
  },
  {
    img: "/assets/equipo/Gaspar.png",
    name: "María José Gaspar",
    role: "Majo",
    carrera: "Diseño Gráfico y Digital",
    frase:"Viva la vida",
    experiencia:"Maravillosa",
  },
  {
    img: "/assets/equipo/Reyes.png",
    name: "Ariadna Reyes Alvarado",
    role: "Ari",
    carrera: "Diseño de Productos",
    frase:"La vida no se trata de encontrarte a ti mismo, sino de crearte a ti mismo.",
    experiencia:"Aprender más sobre un diseño colaborativo con otras carreras, las retroalimentaciones y tener satisfacción de lo que se hace para una buena causa, como lo es ITASO",
  },
  {
    img: "/assets/equipo/Davila.png",
    name: "Bruno Dávila Reyes",
    role: "Brune",
    carrera: "diseño de Productos",
    frase:"Si eres bueno en algo, no lo haces gratis.",
    experiencia:"Aprender y hacer amigos.",
  },
  {
    img: "/assets/equipo/Galnares.png",
    name: "Diego Galnares Llaca",
    role: "Galna",
    carrera: "Ciencias de la comunicación",
    frase:"Si tienes tiempo para sentir pena por tí mismo, entonces tienes tiempo para superarte",
    experiencia:"Poder crecer profesionalmente, usar lo que ya he aprendido, y aprender cosas nuevas para mejorar.",
  },
  {
    img: "/assets/equipo/Esquivel.png",
    name: "Emilio Esquivel Vargas",
    role: "Manchego",
    carrera: "Ciencias de la comunicación",
    frase:"Caminante no hay camino, se hace camino al andar",
    experiencia:"Espero poder adquirir herramientas adicionales que puedan complementar mis estudios y formación humanista para ayudar a las personas",
  },
  {
    img: "/assets/equipo/Caballero.png",
    name: "Karina Caballeros Angeles",
    role: "Caba",
    carrera: "Ingeniería Cibernética",
    frase:"No te preocupes, se feliz",
    experiencia:"Aprender del proyecto y poder ver el impacto del proyecto",
  },
  {
    img: "/assets/equipo/Prado.png",
    name: "Julio Prado",
    role: "Julián",
    carrera: "Ingeniería Cibernética",
    frase:"No hagas las cosas hasta que te salgan bien, hazlas hasta que no te pueda salir mal",
    experiencia:"Mucho conocimiento sobre temas medicos como la nutricion y la higiene de sueño, ademas del entendimiento de equipos tansversales para llegar a un solo objetivo. Las redes neruonales aplicadas a la medicina para la deteccion de padecimientos de manera temprana",
  },
  {
    img: "/assets/equipo/Carracedo.png",
    name: "Ana Sofía Carracedo",
    role: "Chofis",
    carrera: "Diseño gráfico y Digital",
    frase:"Nuestra vida es lo que nuestros pensamientos crean",
    experiencia:"Que sea una oportunidad para impactar positivamente en la comunidad y aprender de experiencias enriquecedoras",
  },
  {
    img: "/assets/equipo/HernandezVa.png",
    name: "Victoria Hernández Varela",
    role: "Vicho",
    carrera: "Diseño Gráfico y Digital",
    frase:"La ciencia moderna aún no ha producido un medicamento tranquilizador tan eficaz como lo son unas pocas palabras bondadosas ",
    experiencia:"Mi experiencia en ITASO fue muy agradable, los profesionales con los que pude convivir fueron muy amables y me da mucha alegría lo que busca el proyecto y que haya personas preocupadas por situaciones cómo estás.",
  },
  {
    img: "/assets/equipo/HernandezMa.png",
    name: "Eduardo Hernández Martinez",
    role: "Edu",
    carrera: "Diseño Gráfico y digital",
    frase:"No hay fecha que no llegue, el tiempo es sabio",
    experiencia:"Que sea una experiencia positiva en mi carrera profesional",
  },
  {
    img: "/assets/equipo/Granados.png",
    name: "Martín Granados",
    role: "Martín",
    carrera: "Ingeniería cibernética",
    frase:"No existe el fracaso, salvo cuando dejamos de esforzarnos",
    experiencia:"Fue una experieccia muy buena ya que pude crear herramientas para ayudar a los demas al mismo tiempo que apredí cosas que creia saber",
  },
  {
    img: "/assets/equipo/Blanco.png",
    name: "Luis Blanco",
    role: "Blanco",
    carrera: "Ingeniería Cibernética",
    frase:"Sube escalón por escalón hasta que ese escalón sea la cima",
    experiencia:"Estuvo padre la experiencia ya que pude reforzar mis conocimientos de desarrollo web y dando mejor estructura a los archivos.",
  },
  {
    img: "/assets/equipo/Azamar.png",
    name: "Sebastián Azamar",
    role: "Sebas",
    carrera: "Ingeniería Cibernética",
    frase:"Se el cambio que quieras ver en el mundo",
    experiencia:"Pude ser capaz de aplicar los conocimientos de mi carrera en un ambito distinto al acostumbrado, además de poder trabajar con carreras además de la mia",
  },
  {
    img: "/assets/equipo/SF.jpg",
    name: "Jorge David Cruz Monroy",
    role: "Jorge",
    carrera: "Diseño de productos",
    frase:"¿Porqué caemos? Para aprender a levantarnos",
    experiencia:"Espero poner a prueba mis habilidades y fortalecerlas para poder entregar excelentes resultados a Itaso",
  },
  {
    img: "/assets/equipo/SF.jpg",
    name: "Cesár Alberto Meza Ángulo",
    role: "Shiza",
    carrera: "Diseño de productos",
    frase:"Jálate weeee",
    experiencia:"Pues hago lo que me gusta y espero poder aprender más sobre el área en la que me quiero especializar",
  },
  {
    img: "/assets/equipo/SF.jpg",
    name: "Hannia Vanessa Bucio Godínez ",
    role: "Hannia",
    carrera: "Mercadotecnia",
    frase:"Un buen día hace la diferencia",
    experiencia:" me gustaría muchísimo aprender a trabajar con diferentes áreas en un tema súper importante como lo es la salud para los niños",
  },
  {
    img: "/assets/equipo/SF.jpg",
    name: "Sebastian López Hernández",
    role: "Sebas",
    carrera: "Diseño Gráfico y Digital",
    frase:"Se valiente y Amable",
    experiencia:"Espero poder trabajar en equipo para alcanzar una meta significativa",
  },
  {
    img: "/assets/equipo/SF.jpg",
    name: "Carlos Andrés Rivas Gutiérrez",
    role: "Andrés",
    carrera: "Ingeniería cibernética y sistemas computacionales",
    frase:"Per audacia ad astra",
    experiencia:"Espero poder contribuir a la causa del proyecto para poder ayudar y apoyar",
  },
];

export const carouselData = [
  {
    imageSrc:
      "/assets/rallys/VI_Rally_Bienestar_Integral_ITASO-MX_RS_2205-163 (1).jpg",
    title: "First slide label",
    description: "Nulla vitae elit libero, a pharetra augue mollis interdum.",
  },
  {
    imageSrc:
      "/assets/rallys/VI_Rally_Bienestar_Integral_ITASO-MX_RS_2205-64.jpg",
    title: "Second slide label",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    imageSrc:
      "/assets/rallys/VI_Rally_Bienestar_Integral_ITASO-MX_RS_2205-93.jpg",
    title: "Third slide label",
    description:
      "Praesent commodo cursus magna, vel scelerisque nisl consectetur.",
  },
];
